 SELECT DISTINCT ?sensor
WHERE {
{?observation <http://knoesis.wright.edu/ssw/ont/sensor-observation.owl#procedure> ?sensor .
?observation <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://knoesis.wright.edu/ssw/ont/weather.owl#PrecipitationObservation> .
?observation <http://linkeddata.com/ontology#hasResult> ?result .
}GJOIN 
{
{
?observation <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://knoesis.wright.edu/ssw/ont/weather.owl#PrecipitationObservation> .
FILTER (!regex(str(?observation),'http://linkeddata.com/ontology#','i'))
}
UNION 
{
?observation <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://knoesis.wright.edu/ssw/ont/weather.owl#PrecipitationObservation> .
?observation <http://linkeddata.com/ontology#hasOrder> ?obsorder .
?obsorder ?p ?obselement .
FILTER (?p != <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> )
}
}
