SELECT DISTINCT ?value
 WHERE { 
{?observation <http://knoesis.wright.edu/ssw/ont/sensor-observation.owl#procedure> ?sensor .
?observation <http://knoesis.wright.edu/ssw/ont/sensor-observation.owl#observedProperty> <http://knoesis.wright.edu/ssw/ont/weather.owl#_WindSpeed> .
?observation <http://linkeddata.com/ontology#hasResult> [ <http://knoesis.wright.edu/ssw/ont/sensor-observation.owl#floatValue> ?value ] .
}
GJOIN
{{
?observation <http://knoesis.wright.edu/ssw/ont/sensor-observation.owl#observedProperty> <http://knoesis.wright.edu/ssw/ont/weather.owl#_WindSpeed> .
FILTER (!regex(str(?observation),'http://linkeddata.com/ontology#','i'))
}
UNION
{
?observation <http://linkeddata.com/ontology#hasOrder> ?obsorder .
?observation <http://knoesis.wright.edu/ssw/ont/sensor-observation.owl#observedProperty> <http://knoesis.wright.edu/ssw/ont/weather.owl#_WindSpeed> .
?obsorder ?p ?observationelement .
FILTER (?p != <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> )}}
}
