SELECT DISTINCT ?sensor
WHERE {
{?temperatureObservation  <http://knoesis.wright.edu/ssw/ont/sensor-observation.owl#procedure> ?sensor .
?temperatureObservation <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://knoesis.wright.edu/ssw/ont/weather.owl#TemperatureObservation> .
?temperatureObservation <http://linkeddata.com/ontology#hasResult> ?temperatureResult .
FILTER (!regex(str(?temperatureObservation),'http://linkeddata.com/ontology#','i'))
?temperatureResult <http://knoesis.wright.edu/ssw/ont/sensor-observation.owl#floatValue> ?temperature .
?temperatureResult <http://knoesis.wright.edu/ssw/ont/sensor-observation.owl#uom> ?uom .
FILTER(?temperature > "32"^^<http://www.w3.org/2001/XMLSchema#float>)
?windSpeedObservation <http://knoesis.wright.edu/ssw/ont/sensor-observation.owl#procedure> ?sensor .
?windSpeedObservation <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://knoesis.wright.edu/ssw/ont/weather.owl#WindSpeedObservation> .
?windSpeedObservation <http://linkeddata.com/ontology#hasResult> [ <http://knoesis.wright.edu/ssw/ont/sensor-observation.owl#floatValue> ?windSpeed ]  
FILTER (!regex(str(?windSpeedObservation),'http://linkeddata.com/ontology#','i'))
}
UNION
{?temperatureObservation  <http://knoesis.wright.edu/ssw/ont/sensor-observation.owl#procedure> ?sensor .
?temperatureObservation <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://knoesis.wright.edu/ssw/ont/weather.owl#TemperatureObservation> .
?temperatureObservation <http://linkeddata.com/ontology#hasResult> ?temperatureResult .
?temperatureObservation <http://linkeddata.com/ontology#hasOrder> ?temporder .
?temperatureResult <http://knoesis.wright.edu/ssw/ont/sensor-observation.owl#floatValue> ?temperature .
?temperatureResult <http://knoesis.wright.edu/ssw/ont/sensor-observation.owl#uom> ?uom .
FILTER(?temperature > "32"^^<http://www.w3.org/2001/XMLSchema#float>)
?temporder ?p1 ?temperatureelement .
FILTER (?p1 != <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> )
?windSpeedObservation <http://knoesis.wright.edu/ssw/ont/sensor-observation.owl#procedure> ?sensor .
?windSpeedObservation <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://knoesis.wright.edu/ssw/ont/weather.owl#WindSpeedObservation> .
?windSpeedObservation <http://linkeddata.com/ontology#hasResult> [ <http://knoesis.wright.edu/ssw/ont/sensor-observation.owl#floatValue> ?windSpeed ]  
?windSpeedObservation <http://linkeddata.com/ontology#hasOrder> ?windspeedorder .
?windspeedorder ?p2 ?windspeedelement .
FILTER (?p2 != <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> )

}
}

